version: "3"

services:
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eshop_db
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=password
    container_name: handson-cloud-msa_postgres

  postgres_ad:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/ad
    environment:
      - POSTGRES_DB=eshop_db_ad
      - POSTGRES_USER=eshop_user_ad
      - POSTGRES_PASSWORD=password_ad
    container_name: handson-cloud-msa_postgres_ad  

  postgres_shipping:
    image: postgres:13
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/shipping
    environment:
      - POSTGRES_DB=eshop_db_shipping
      - POSTGRES_USER=eshop_user_shipping
      - POSTGRES_PASSWORD=password_shipping
    container_name: handson-cloud-msa_postgres_shipping  
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
