version: "3"

services:
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eshop_db
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=password
    container_name: handson-cloud-msa_postgres

  postgres_ad:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/ad
    environment:
      - POSTGRES_DB=eshop_db_ad
      - POSTGRES_USER=eshop_user_ad
      - POSTGRES_PASSWORD=password_ad
    container_name: handson-cloud-msa_postgres_ad  

