eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
spring:
  application:
    name: MONOLITHIC
  datasource:
    initialization-mode: always
    password: password
    url: jdbc:postgresql://localhost:5432/eshop_db
    username: eshop_user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  redis:
    host: localhost
    port: 6379
  resources:
    cache:
      cachecontrol:
        max-age: 3600

