server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: monolithic
          uri: lb://MONOLITHIC
          predicates:
            - Path=/**
        - id: ad
          uri: lb://AD
          predicates:
            - Path=/ads/**                        
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE