server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
        - id: ad
          uri: lb://AD
          predicates:
            - Path=/ads/**
        - id: currency
          uri: lb://CURRENCY
          predicates:
            - Path=/currencies/**
        - id: shipping
          uri: lb://SHIPPING
          predicates:
            - Path=/shippings/**
        - id: monolithic
          uri: lb://MONOLITHIC
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE